Do-Dolphin/dolphin

- src/main/java/com/dolphin/demo/excetion/CustomException.java
- src/main/java/com/dolphin/demo/excetion/ErrorCode.java
- src/main/java/com/dolphin/demo/excetion/ErrorResponse.java
- src/main/java/com/dolphin/demo/excetion/Exception.java
- src/main/java/com/dolphin/demo/excetion/ExceptionHandler.java
> 이셉션 핸들러 추가

- build.gradle
- src/main/java/com/dolphin/demo/Configration/RedisConfig.java
- src/main/java/com/dolphin/demo/Configration/WebSecurityConfig.java
- src/main/java/com/dolphin/demo/Controller/MemberController.java
- src/main/java/com/dolphin/demo/domain/Member.java
- src/main/java/com/dolphin/demo/dto/requestDto/LoginRequestDto.java
- src/main/java/com/dolphin/demo/dto/requestDto/SignupRequestDto.java
- src/main/java/com/dolphin/demo/exception/CustomException.java
- src/main/java/com/dolphin/demo/exception/ErrorCode.java
- src/main/java/com/dolphin/demo/exception/ErrorResponse.java
- src/main/java/com/dolphin/demo/exception/Exception.java
- src/main/java/com/dolphin/demo/exception/ExceptionHandler.java
- src/main/java/com/dolphin/demo/jwt/JwtAuthenticationFilter.java
- src/main/java/com/dolphin/demo/jwt/JwtExceptionFilter.java
- src/main/java/com/dolphin/demo/jwt/JwtExceptionResponse.java
- src/main/java/com/dolphin/demo/jwt/JwtTokenProvider.java
- src/main/java/com/dolphin/demo/jwt/UserDetailsImpl.java
- src/main/java/com/dolphin/demo/jwt/UserDetailsServiceImpl.java
- src/main/java/com/dolphin/demo/repository/MemberRepository.java
- src/main/java/com/dolphin/demo/service/MemberService.java
- src/main/java/com/dolphin/demo/service/RedisService.java
> 회원가입, 로그인 기능 추가

- src/main/java/com/dolphin/demo/DemoApplication.java
- src/main/java/com/dolphin/demo/configuration/RedisConfig.java
- src/main/java/com/dolphin/demo/configuration/WebSecurityConfig.java
- src/main/java/com/dolphin/demo/controller/MemberController.java
- src/main/java/com/dolphin/demo/controller/SocialLoginController.java
- src/main/java/com/dolphin/demo/dto/requestDto/KakaoUserInfoDto.java
- src/main/java/com/dolphin/demo/dto/requestDto/LoginRequestDto.java
- src/main/java/com/dolphin/demo/service/KakaoLoginService.java
- src/main/java/com/dolphin/demo/service/MemberService.java
> 카카오 소셜 로그인 기능 추가

- src/main/java/com/dolphin/demo/service/AmazonS3Service.java
- src/main/java/com/dolphin/demo/service/CommentService.java
> 이미지 URL 생성 로직 및 후기 수정 로직 변경

- src/main/java/com/dolphin/demo/controller/CommentController.java
- src/main/java/com/dolphin/demo/controller/EventController.java
- src/main/java/com/dolphin/demo/domain/Comment.java
- src/main/java/com/dolphin/demo/domain/CommentImage.java
- src/main/java/com/dolphin/demo/domain/Event.java
- src/main/java/com/dolphin/demo/dto/request/EventRequestDto.java
- src/main/java/com/dolphin/demo/dto/response/CommentResponseDto.java
- src/main/java/com/dolphin/demo/dto/response/EventResponseDto.java
- src/main/java/com/dolphin/demo/repository/CommentRepository.java
- src/main/java/com/dolphin/demo/repository/EventRepository.java
- src/main/java/com/dolphin/demo/service/AmazonS3Service.java
- src/main/java/com/dolphin/demo/service/CommentService.java
- src/main/java/com/dolphin/demo/service/EventService.java
> 배너용 축제 기능 구현

- src/main/java/com/dolphin/demo/dto/request/CommentRequestDto.java
> 후기 star 필수 입력으로 변경

- src/main/java/com/dolphin/demo/dto/request/CommentRequestDto.java
> 후기 star 필수값으로 변경

- src/main/java/com/dolphin/demo/controller/EmailController.java
- src/main/java/com/dolphin/demo/controller/MemberController.java
- src/main/java/com/dolphin/demo/dto/request/AuthEmailRequestDto.java
- src/main/java/com/dolphin/demo/dto/request/MemberOutDto.java
- src/main/java/com/dolphin/demo/jwt/JwtTokenProvider.java
- src/main/java/com/dolphin/demo/service/EmailService.java
- src/main/java/com/dolphin/demo/service/MemberService.java
Feature/sse 회원탈퇴 기능 추가, 이메일 재인증시 이전 이메일코드만료
> Feature/sse 회원탈퇴 기능 추가, 이메일 재인증시 이전 이메일코드만료

- build.gradle
- src/main/java/com/dolphin/demo/controller/SearchController.java
- src/main/java/com/dolphin/demo/dto/response/PlaceSearchDto.java
- src/main/java/com/dolphin/demo/repository/PlaceRepository.java
- src/main/java/com/dolphin/demo/repository/PlaceRepositoryCustom.java
- src/main/java/com/dolphin/demo/repository/PlaceRepositoryImpl.java
> 여행지 키워드로 검색 기능 구현

- build.gradle
> build.gradle 설정 변경

- src/main/java/com/dolphin/demo/repository/PlaceRepositoryImpl.java
> 여행지 키워드 검색 기능 구현

- src/main/java/com/dolphin/demo/controller/SearchController.java
- src/main/java/com/dolphin/demo/repository/PlaceRepositoryCustom.java
- src/main/java/com/dolphin/demo/repository/PlaceRepositoryImpl.java
검색시 공백 제거
- ex) "닭갈비", "닭 갈비" 를 "닭갈비"로 동일하게 검색되도록 수정
지역선택 검색 기능 추가
- 지역코드와 시군구코드를 입력하면 해당 지역 내 키워드만 검색되도록 수정
> 검색시 공백제거, 지역선택 검색 기능 추가

- src/main/java/com/dolphin/demo/repository/PlaceRepositoryImpl.java
> 시군구 전체 검색시 조건 추가

- src/main/java/com/dolphin/demo/controller/SearchController.java
- src/main/java/com/dolphin/demo/repository/PlaceRepositoryImpl.java
여행지 검색시 여행지 타이틀과 검색어의 공백을 제거한 후 검색 되도록 수정
> 여행지 검색시 여행지 타이틀과 검색어의 공백을 제거한 후 검색 되도록 수정

- build.gradle
- src/main/java/com/dolphin/demo/controller/WorldCupController.java
- src/main/java/com/dolphin/demo/service/WorldCupService.java
이상형월드컵 컨트롤, 서비스 추가
일단 32강 처음 랜덤으로 뽑아서 보내주는 메서드만 커밋
> 이상형월드컵 컨트롤, 서비스 커밋

- src/main/java/com/dolphin/demo/controller/WorldCupController.java
- src/main/java/com/dolphin/demo/dto/request/WorldCupRequestDto.java
- src/main/java/com/dolphin/demo/dto/response/WorldCupResponseDto.java
- src/main/java/com/dolphin/demo/service/WorldCupService.java
> 월드컵 선출반환 메서드 추가

- src/main/java/com/dolphin/demo/controller/WorldCupController.java
- src/main/java/com/dolphin/demo/repository/PlaceRepository.java
- src/main/java/com/dolphin/demo/service/WorldCupService.java
> 이상형 월드컵 필터(전체지역, 세부지역, 테마) 추가

- src/main/java/com/dolphin/demo/controller/WorldCupController.java
- src/main/java/com/dolphin/demo/service/WorldCupService.java
> 찜한 지역 이상형 월드컵 추가

- src/main/java/com/dolphin/demo/dto/request/ImageRequestDto.java
ImageRequestDto Validation 관련 어노테이션 수정
> ImageRequestDto Validation 관련 어노테이션 수정

- src/main/java/com/dolphin/demo/configuration/WebSecurityConfig.java
> 여행코스용 CORS 추가
